#!/usr/bin/python3
from sys import argv


def factorize_func(value):
    i = 2

    if value < 2:
        return
    print()
    print(value, "<- value-bef")
    while value % i:
        i += 1
    print("{:.0f}={:.0f}*{:.0f}".format(value, value / i, i))
    print(value, "<- value-aft")
    print()


if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as file_name:
        line = file_name.readline()

        while line != "":
            value = int(line.split('\n')[0])
            factorize_func(value)
            line = file_name.readline()
except (IndexValue):
    pass
